# Flujo de trabajo simple para implementar contenido estático en Github Pages
name: Implementar contenido estático a Pages

on:
  # Se ejecuta en anotaciones dirigidas a la rama predeterminada
  push:
    branches: ["master"]

  # Te permite ejecutar este flujo de trabajo manualmente desde la pestaña Acciones
  workflow_dispatch:

# Establece los permisos de GITHUB_TOKEN para permitir la implementación en GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Permite una implementación simultánea
concurrency:
  group: "pages"
  cancel-in-progress: true

env: 
    VITE_APP_NAME: ${{ secrets.VITE_APP_NAME }}
    VITE_APP_MODE_DEV: ${{ env.VITE_APP_MODE_DEV}}
jobs:
  # Trabajo de implementación único ya que solo estamos implementando
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
  runs-on: ubuntu-latest
  steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Node
      uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: "npm"
    - name: Enviroment
      run: cp env.json.example env.json
    - name: Instalando dependecias
      run: npm install
    - name: Build
      run: npm run build
    - name: Configurando Pages
      uses: actions/configure-pages@v3
    - name: Subiendo dist
      uses: actions/upload-pages-artifact@v2
      with:
        # Subir repositorio dist
        path: "./dist"
    - name: Deploy en GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v2
